In [1]:
import numpy as np

#### 72. How to swap two rows of an array? (★★★)

In [88]:
def change_rows(arr, row1, row2):
    arr[[row1-1]], arr[[row2-1]] = arr[[row2-1]], arr[[row1-1]]
    print(arr)

arr = np.array([[1,2,3], [3,2,1], [2,4,6], [6,4,2]])
change_rows(arr, 2, 4)

[[1 2 3]
 [6 4 2]
 [2 4 6]
 [3 2 1]]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [5]:
def sliding_average(array, n):
    #define the size of the rolling window by n
    s = np.cumsum(array)
    print(s)
    print(s[n:] - s[:-n])
    return (s[n:] - s[:-n]) /n

arr = np.arange(20)
print(arr)
print(sliding_average(arr, 3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]
[ 6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
