In [1]:
import numpy as np

#### 72. How to swap two rows of an array? (★★★)

In [6]:
def change_rows(arr, row1, row2):
    arr[[row1-1]], arr[[row2-1]] = arr[[row2-1]], arr[[row1-1]]
    print(arr)

arr = np.array([[1,2,3], [3,2,1], [2,4,6], [6,4,2]])
print(arr)
change_rows(arr, 2, 4)

[[1 2 3]
 [3 2 1]
 [2 4 6]
 [6 4 2]]
[[1 2 3]
 [6 4 2]
 [2 4 6]
 [3 2 1]]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [45]:
def sliding_average(array, n):
    s = np.cumsum(array)
    s[n:] = s[n:] - s[:-n]
    return s[n:] / n

arr = np.arange(10)
sliding_average(arr, 4)

array([2.5, 3.5, 4.5, 5.5, 6.5, 7.5])